apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-container
          image: yashtiwarii/spe_backend
          ports:
            - name: http
              containerPort: 3001
          env:
            - name: MONGO_URI
              value: "mongodb+srv://yash2411:yash2411@cluster0.sb3jj38.mongodb.net/?retryWrites=true&w=majority"
            - name: PORT
              value: "3001"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app
spec:
  type: LoadBalancer
  selector:
    app: backend-app
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001
      # nodePort: 30001